rules_folder: /opt/elastalert/rules

run_every:
  minutes: 5

buffer_time:
  minutes: 15

es_host: elasticsearch
es_port: 9200
es_username: elastic_alert # username of authorized ElasticSearch account
es_password: password      # password of authorized ElasticSearch account

writeback_index: elastalert_status

alert_time_limit:
  days: 2